name: Java Spring Boot CI for SoftClick_api
run-name: ${{ github.actor }} opened/reopened a pull request to ${{ github.base_ref }} from ${{ github.head_ref }}
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - develop
      - releases/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
#      - name: Fetch asset
#        run: gh release download --repo SoftClick-for-project-managment/SoftClick_data 5
#        env:
#          GITHUB_TOKEN: ${{ secrets.SOFTCLICK_DATA_REPO_TOKEN }}
#      - name: See what we downloaded
#        run: ls
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        env:
          SOFTCLICK_DATA_HOST: ${{ secrets.SOFTCLICK_DATA_QA_HOST }}
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: softclick_api
          path: staging